definitions:
  handler.Response:
    properties:
      data: {}
      message:
        type: string
      success:
        type: boolean
    type: object
  payment.InputPayment:
    properties:
      product_id:
        type: integer
    required:
    - product_id
    type: object
  payment.Payment:
    properties:
      created_at:
        type: string
      id:
        type: integer
      price_paid:
        type: number
      product_id:
        type: integer
      updated_at:
        type: string
    type: object
  product.InputProduct:
    properties:
      name:
        type: string
      price:
        type: number
    required:
    - name
    - price
    type: object
  product.Product:
    properties:
      created_at:
        type: string
      id:
        type: integer
      name:
        type: string
      price:
        type: number
      updated_at:
        type: string
    type: object
info:
  contact: {}
paths:
  /payment:
    get:
      consumes:
      - application/json
      description: get all payments
      parameters:
      - description: get all payments
        in: query
        name: q
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/payment.Payment'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.Response'
      summary: List payments
      tags:
      - payments
    post:
      consumes:
      - application/json
      description: add payment
      parameters:
      - description: Add payment
        in: body
        name: id
        required: true
        schema:
          type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/payment.InputPayment'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.Response'
      summary: Post a new payment
      tags:
      - payments
  /payment/{id}:
    delete:
      consumes:
      - application/json
      description: delete payment by ID
      parameters:
      - description: Payment ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.Response'
      summary: Delete a payment
      tags:
      - payments
    get:
      consumes:
      - application/json
      description: get payment by ID
      parameters:
      - description: Payment ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/payment.Payment'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.Response'
      summary: Show a payment
      tags:
      - payments
    put:
      consumes:
      - application/json
      description: update payment by ID
      parameters:
      - description: update payments
        in: body
        name: id
        required: true
        schema:
          type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/payment.InputPayment'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.Response'
      summary: Update a payment
      tags:
      - payments
  /payment/stream:
    get:
      consumes:
      - application/json
      description: Stream
      parameters:
      - description: stream
        in: body
        name: q
        required: true
        schema:
          type: array
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              type: boolean
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.Response'
      summary: Stream
      tags:
      - stream
  /product:
    get:
      consumes:
      - application/json
      description: get all products
      parameters:
      - description: get all products
        in: query
        name: q
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/product.Product'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.Response'
      summary: List products
      tags:
      - products
    post:
      consumes:
      - application/json
      description: add product
      parameters:
      - description: Add product
        in: body
        name: id
        required: true
        schema:
          type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/product.InputProduct'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.Response'
      summary: Post a new product
      tags:
      - products
  /product/{id}:
    delete:
      consumes:
      - application/json
      description: delete product by ID
      parameters:
      - description: Product ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.Response'
      summary: Delete a product
      tags:
      - products
    get:
      consumes:
      - application/json
      description: get product by ID
      parameters:
      - description: Product ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/product.Product'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.Response'
      summary: Show an product
      tags:
      - products
    put:
      consumes:
      - application/json
      description: update product by ID
      parameters:
      - description: update product
        in: body
        name: id
        required: true
        schema:
          type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/product.InputProduct'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.Response'
      summary: Update a product
      tags:
      - products
swagger: "2.0"
